//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateTable
    {
        public int Id { get; set; }
        public string Candidate { get; set; }
        public string IsProcessed { get; set; }
        public string MeetingId { get; set; }
        public string SenderId { get; set; }
    }
}
